# hostname (and path) to the root eg. http://spf13.com/
baseurl: "/" # In most cases this will work.

# baseurl: http://www.metabates.com
# disablePathToLower: true
languageCode: en-us
title: Mark Bates

pygmentsstyle: "monokai"
PygmentsCodeFences: true
pygmentsuseclasses: true

theme: "bootstrap"

  # Site title
title: "MetaBates.com"

  # Copyright
copyright: "(c) 2016 Mark Bates."

  # Pagination
paginate: 10
paginatePath: "page"

  # Enable Disqus integration
disqusShortname: "metabates"

permalinks:
  post: "/:year/:month/:day/:slug/"
  code: "/:slug/"

taxonomies:
 tag: "tags"

author:
  name: "Mark Bates"
  email: "mark+blog@markbates.com"

    #
    # All parameters below here are optional and can be mixed and matched.
    #

  # bootswatch theme name, unmark and select one: cerulean, cosmo, cyborg, darkly,
  # default, flatly, journal,  lumen, paper, readable, sandstone, simplex,
  # slate, spacelab, superhero, united, yeti.

params:

    # You can use markdown here.
  BrandImage: "" #top header brand image.
  # BrandImage: "http://blog.appernetic.io/images/apperneticlogo.png" #top header brand image.
  brand: "Mark Bates" # brand image alt text.
  topline: "The technical ramblings of Mark Bates."
  footline: "code with <i class='fa fa-heart'></i>"

    # Show a sidebar menu
  showRightSidebar: true

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
  home: "home"

  mailmunchid: "" # Mailmunch site id
  sumomeid: "" # Sumome id

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
  highlight: "monokai_sublime"

    # Google Analytics.
  googleAnalytics: "UA-9756583-1"

    # Sidebar social links.
  github: "markbates" # Your Github profile ID
  bitbucket: "" # Your Bitbucket profile ID
  linkedin: "" # Your LinkedIn profile ID (from public URL)
  googleplus: "" # Your Google+ profile ID
  facebook: "" # Your Facebook profile ID
  twitter: "markbates" # Your Twitter profile ID
  youtube: ""  # Your Youtube channel ID
  flattr: ""  # populate with your flattr uid

  theme:
    name: "cerulean"

  # popover:
  #   # This is a highly configurable popover form.
  #   enablepopover: false #enable or disable popover: true/false.
  #   posturl: "https://zapier.com/hooks/..."
  #   headerimage: "//placehold.it/1000x600"
  #   expirecookie: 5 #show it again after number of days to visitor that has not subscribed.
  #   cookiename: "mycookie1" #give the cookie a unique name variable (avoid spaces and strange characters).
  #   signupheader: "Join Our Newsletter"
  #   showmodaltimeout: 10000 #show popover modal after time interval in milliseconds.
  #   mouseleave: true #show popover when mouse leaves window: true/false.
  #   modalsize: "" #lg or sm. Empty is md. If phone is detected lg is used.
  #   imagedescription: "Placeholder image for this popover modal optin form"
  #   signuptext: "Signup today for free and be the first to get notified on new updates."
  #   inputplaceholder: "Enter your email"
  #   submitbutton: "Subscribe"
  #   successmessage: "Thanks for your subscription!"
  #   errormessage: "Submitting form failed!"
  #   optin: true #opt-in: true/false



  blackfriday:
    angledQuotes: true
    fractions: false
    hrefTargetBlank: false
    latexDashes: true
    plainIdAnchors: true
    extensions: []
    extensionmask: []
